---
title: "Course announcement"
author: "John Doe"
date: today
---

## When and where

21 - 22 March 2024

Air&Fire, SciLifeLab Stockholm
Tomtebodavägen 23A
Solna, Sweden  

<br>
<a class="nice-button" href="https://forms.gle/5F7NWfUMEmCFLgDQ8"> Register
</a>


## How do we build a collaborative and innovative workplace?

In the first offering of this two-day course in Organizational Learning, learn how we can adapt and improve as an organization through gathering, sharing, and applying knowledge. This course goes beyond individual skill development to building organizational culture and structure. Through creating and utilizing organizational processes that foster collective learning and development, we can achieve the workplace we want.

The lectures, discussions, and exercises of this course will teach foundational principles and theories of Organizational Learning, including concepts on organizational knowledge, knowledge management, and workplace training.
We will also give you practical tools and sustainable strategies you can apply beyond the course—such as how to enhance learning at all levels, from the individual (micro level), to group/team (meso level) and organization (macro level).

We welcome managers, coordinators, and leaders from all career stages to learn how to build a workplace culture of continuous learning in a resource-friendly way using organizational knowledge and collective intelligence!

## Targeted level of the training event
Introductory level

## Target Audience
Infrastructure managers, SciLifeLab affiliated group leaders, and other staff with managerial roles.

## Prerequisites
No prior knowledge of organisational learning, management or individual learning is required, but experience from management is beneficial. 

### Learning Outcomes

By the end of this course, participants should be able to:

* explain key concepts in Organisational Learning, and how these relate to culture, leadership and organisational processes.

* identify similarities and differences between individual learning, group learning and organisational learning

* identify workplace learning activities, and recognize how these can be designed to create additional organisational value

* identify barriers and promoters for knowledge dissemination and organisational learning

## Syllabus:
**Day 1 (Thursday 21.3.2024):**                

Module 1 – Introduction to Organisational Learning

Module 2 – Basic concepts of Individual learning

**Day 2 (Friday 22.3.2024):**                     

Module 3 – Concepts of Organisational Learning

Module 4 – How we promote organisational learning

**Spring 2024:**

After the course an optional follow-up session will be held online. Exact date will be decided by the participants.

## Course fee
There is no course attendance fee. Please note that the course does not include any meals or accommodation.

## Selection criteria
Due to limited space, the course accommodates a maximum of 25 participants. If we receive more applications, participants will be selected based on selection criteria such as correct entry requirements, motivation to attend the course as well as gender and geographical balance.

## Important dates
Application open: Jan 25, 2024

Application closes: Feb 20, 2024

Confirmation to applicants Feb 23, 2024

For further questions, please contact us at traininghub@scilifelab.se.